"use client";
import { useEffect,useState } from "react";
type User={id:string;name:string;email:string;role:"admin"|"user"};
async function api(body?:unknown){const r=await fetch("/api/auth",body?{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}:{});const d=await r.json();if(!r.ok)throw new Error(d.error);return d;}
export default function AuthGate({children}:{children:React.ReactNode}){const[user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true),[mode,setMode]=useState<"login"|"register">("login"),[error,setError]=useState(""),[admin,setAdmin]=useState(false),[users,setUsers]=useState<any[]>([]);
 const load=()=>api().then(d=>{setUser(d.user);const left=Math.max(0,d.expiresAt-Date.now());setTimeout(()=>location.reload(),left+500)}).catch(()=>setUser(null)).finally(()=>setLoading(false));useEffect(()=>{load()},[]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError("");const f=new FormData(e.currentTarget);try{await api({action:mode,...Object.fromEntries(f)});await load()}catch(x:any){setError(x.message)}}
 async function openAdmin(){const d=await api({action:"list-users"});setUsers(d.users);setAdmin(true)}
 if(loading)return <div className="authPage"><div className="authCard">Memuat...</div></div>;
 if(!user)return <div className="authPage"><form className="authCard" onSubmit={submit}><div className="authLogo">PG</div><h1>{mode==="login"?"Masuk ke PromptGen":"Buat akun baru"}</h1><p>{mode==="login"?"Gunakan email dan password Anda.":"Akun langsung aktif setelah pendaftaran."}</p>{mode==="register"&&<input name="name" placeholder="Nama lengkap" required/>}<input name="email" type="email" placeholder="Email" required/><input name="password" type="password" minLength={8} placeholder="Password minimal 8 karakter" required/>{error&&<b className="authError">{error}</b>}<button>{mode==="login"?"Masuk":"Daftar Sekarang"}</button><a onClick={()=>{setMode(mode==="login"?"register":"login");setError("")}}>{mode==="login"?"Belum punya akun? Daftar":"Sudah punya akun? Masuk"}</a></form></div>;
 return <><div className="userBar"><span>{user.name} · {user.role}</span>{user.role==="admin"&&<button onClick={openAdmin}>Kelola Pengguna</button>}<button onClick={()=>api({action:"logout"}).then(()=>location.reload())}>Keluar</button></div>{children}{admin&&<div className="adminModal"><div className="adminBox"><button className="adminClose" onClick={()=>setAdmin(false)}>×</button><h2>Kelola Pengguna</h2>{users.map(u=><div className="userRow" key={u.id}><span><b>{u.name}</b><small>{u.email} · {u.role}</small></span>{u.id!==user.id&&<button onClick={()=>api({action:"delete-user",id:u.id}).then(openAdmin)}>Hapus</button>}</div>)}</div></div>}</>}
