import { cookie,currentUser,db,hashPassword,issueSession,random,tokenFrom,sha } from "../../lib/auth";
const json=(data:unknown,status=200,headers?:HeadersInit)=>Response.json(data,{status,headers});
export async function GET(req:Request){const u=await currentUser(req);return u?json({user:{id:u.id,name:u.name,email:u.email,role:u.role},expiresAt:u.expires_at}):json({error:"Belum login"},401);}
export async function POST(req:Request){const body=await req.json<any>();const action=body.action;
 if(action==="register"){const name=String(body.name||"").trim(),email=String(body.email||"").trim().toLowerCase(),password=String(body.password||"");if(name.length<2||!/^\S+@\S+\.\S+$/.test(email)||password.length<8)return json({error:"Nama, email, atau password minimal 8 karakter belum valid."},400);if(await db().prepare("SELECT id FROM users WHERE email=?").bind(email).first())return json({error:"Email sudah terdaftar."},409);const count=await db().prepare("SELECT COUNT(*) total FROM users").first<any>();const salt=random(16),id=crypto.randomUUID();await db().prepare("INSERT INTO users(id,name,email,password_hash,password_salt,role,status,created_at) VALUES(?,?,?,?,?,?,?,?)").bind(id,name,email,await hashPassword(password,salt),salt,Number(count?.total||0)===0?"admin":"user","active",Date.now()).run();const s=await issueSession(id);return json({ok:true,role:Number(count?.total||0)===0?"admin":"user"},201,{"Set-Cookie":cookie(s.token)});}
 if(action==="login"){const email=String(body.email||"").trim().toLowerCase(),password=String(body.password||"");const u=await db().prepare("SELECT * FROM users WHERE email=?").bind(email).first<any>();if(!u||u.status!=="active"||await hashPassword(password,u.password_salt)!==u.password_hash)return json({error:"Email atau password salah."},401);const s=await issueSession(u.id);return json({ok:true},200,{"Set-Cookie":cookie(s.token)});}
 if(action==="logout"){const t=tokenFrom(req);if(t)await db().prepare("DELETE FROM sessions WHERE token_hash=?").bind(await sha(t)).run();return json({ok:true},200,{"Set-Cookie":cookie("",0)});}
 const me=await currentUser(req);if(!me||me.role!=="admin")return json({error:"Akses admin diperlukan."},403);
 if(action==="list-users"){const r=await db().prepare("SELECT id,name,email,role,status,created_at FROM users ORDER BY created_at DESC").all();return json({users:r.results});}
 if(action==="add-user"){const name=String(body.name||"").trim(),email=String(body.email||"").trim().toLowerCase(),password=String(body.password||"");if(name.length<2||password.length<8)return json({error:"Data belum valid."},400);const salt=random(16);try{await db().prepare("INSERT INTO users(id,name,email,password_hash,password_salt,role,status,created_at) VALUES(?,?,?,?,?,'user','active',?)").bind(crypto.randomUUID(),name,email,await hashPassword(password,salt),salt,Date.now()).run();return json({ok:true});}catch{return json({error:"Email sudah digunakan."},409);}}
 if(action==="delete-user"){if(body.id===me.id)return json({error:"Admin tidak dapat menghapus akun sendiri."},400);await db().prepare("DELETE FROM users WHERE id=?").bind(body.id).run();return json({ok:true});}
 return json({error:"Aksi tidak dikenal."},400);
}
